/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 kucica100.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kucica100.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.295, 0.002, -0.001]}>
        <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={nodes.Cube002_2.material} />
      </group>
      <mesh geometry={nodes.front.geometry} material={nodes.front.material} position={[-0.295, 0.002, -0.001]} />
    </group>
  )
}

useGLTF.preload('/kucica100.glb')
